baseURL = "/"
languageCode = "en-us"
theme = "terminal"
title = "Catid's Hacks"
paginate = 8

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  #contentTypeName = "content/posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true

  # set a custom favicon (default is a `themeColor` square)
  favicon = "img/favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = true # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "MrCatid"
  site = "https://twitter.com/MrCatid"

[languages]
  [languages.en]
    languageName = "English"
    title = "Catid's Hacks"
    subtitle = "Better than kinky sex with models"
    owner = "catid"
    keywords = ""
    copyright = ""
    menuMore = ":: Pinned"
    readMore = ":: Read"
    readOtherPosts = ":: Other posts"
    newerPosts = ":: Newer posts"
    olderPosts = ":: Older posts"
    missingContentMessage = ":: Page not found..."
    missingBackButtonLabel = ":: Return"

    [languages.en.params.logo]
      logoText = "Catid's Hacks"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "backstory"
        name = "Game Hacking Backstory"
        url = "/backstory"
      [[languages.en.menu.main]]
        identifier = "alignment"
        name = "Robust Image Alignment"
        url = "/posts/lk40years"
      [[languages.en.menu.main]]
        identifier = "tiny_sr"
        name = "Learned Upsampling at 60 FPS"
        url = "/posts/tiny_sr"
      [[languages.en.menu.main]]
        identifier = "pack10"
        name = "Pack10: 16-bit Raw Video"
        url = "/posts/pack10"
